export const catalog = {
  watches: [
    {
      title: "TANK MUST WATCH",
      popular: "popular",
      amount: 20,
      shortDescription: "Large model, high autonomy quartz movement, steel",
      price: 3350,
      year: 2019,
      fullDescription: "Tank Must watch, large model, high autonomy quartz movement. Steel case, beaded crown set with a synthetic cabochon-shaped spinel, silvered dial, blued-steel sword-shaped hands, interchangeable steel bracelet. Case dimensions: 33.7 mm x 25.5 mm, thickness: 6.6 mm. Water-resistant up to 3 bar (approx. 30 meters/100 feet).",
      gender: "for her",
      material: "steel",
      shape: "rectangular",
      movement: "quartz",
      strap: "metal"
    },
    {
      title: "TANK MUST WATCH-M",
      popular: "popular",
      amount: 20,
      shortDescription: "Large model, high autonomy quartz movement, steel",
      price: 3350,
      year: 2015,
      fullDescription: "Tank Must watch, large model, high autonomy quartz movement. Steel case, beaded crown set with a synthetic cabochon-shaped spinel, silvered dial, blued-steel sword-shaped hands, interchangeable steel bracelet. Case dimensions: 33.7 mm x 25.5 mm, thickness: 6.6 mm. Water-resistant up to 3 bar (approx. 30 meters/100 feet).",
      gender: "for him",
      material: "steel",
      shape: "rectangular",
      movement: "quartz",
      strap: "metal"
    },
    {
      title: "TANK FRANÇAISE WATCH",
      popular: "popular",
      amount: 19,
      shortDescription: "Small model, quartz movement, steel",
      price: 3550,
      year: 2016,
      fullDescription: "Tank Française watch, small model, quartz movement. Steel case, octagonal crown set with a synthetic cabochon-shaped spinel, silver-grained dial, blued-steel sword-shaped hands, sapphire crystal, steel bracelet. Case dimensions: 25 mm x 20 mm, thickness: 6.15 mm. Water-resistant up to 3 bar (approx. 30 meters/100 feet).",
      gender: "for her",
      material: "steel",
      shape: "rectangular",
      movement: "quartz",
      strap: "metal"
    },
    {
      title: "SANTOS-DUMONT WATCH",
      popular: "popular",
      amount: 17,
      shortDescription: "Small model, quartz movement, steel, leather",
      price: 3750,
      year: 2015,
      fullDescription: "Santos-Dumont watch, small model, high autonomy quartz movement (~ 6 years). Steel case, beaded crown set with a blue synthetic cabochon-shaped spinel, satin-brushed silver dial with sunray effect, Roman numerals, blued-steel sword-shaped hands, sapphire crystal. Strap in navy blue alligator leather, with steel ardillon buckle. Case dimensions: 38 mm x 27.5 mm, thickness: 7.3 mm. Water-resistant up to 3 bar (approx. 30 meters/100 feet).",
      gender: "for her",
      material: "steel",
      shape: "square",
      movement: "quartz",
      strap: "leather"
    },
    {
      title: "RONDE MUST DE CARTIER WATCH",
      popular: "popular",
      amount: 20,
      shortDescription: "40 mm, automatic movement, steel",
      price: 4200,
      year: 2015,
      fullDescription: "Ronde Must de Cartier watch, 40 mm, mechanical movement with automatic winding, caliber 1847 MC. Steel case, beaded crown set with a synthetic cabochon-shaped spinel, sandblasted silver dial, blued-steel sword-shaped hands, sapphire crystal, steel strap fitted with an interchangeability system. Thickness: 9.62 mm. Water-resistant to 3 bar (approx. 30 meters/100 feet).",
      gender: "for her",
      material: "steel",
      shape: "round",
      movement: "automatic",
      strap: "metal"
    },
    {
      title: "RONDE MUST DE CARTIER WATCH-M",
      popular: "popular",
      amount: 19,
      shortDescription: "40 mm, automatic movement, steel",
      price: 4200,
      year: 2016,
      fullDescription: "Ronde Must de Cartier watch, 40 mm, mechanical movement with automatic winding, caliber 1847 MC. Steel case, beaded crown set with a synthetic cabochon-shaped spinel, sandblasted silver dial, blued-steel sword-shaped hands, sapphire crystal, steel strap fitted with an interchangeability system. Thickness: 9.62 mm. Water-resistant to 3 bar (approx. 30 meters/100 feet).",
      gender: "for him",
      material: "steel",
      shape: "round",
      movement: "automatic",
      strap: "metal"
    },
    {
      title: "CLÉ DE CARTIER WATCH",
      popular: "popular",
      amount: 20,
      shortDescription: "31mm, automatic movement, steel",
      price: 4400,
      year: 2021,
      fullDescription: "Clé de Cartier watch, 31 mm, mechanical movement with automatic winding. Steel case, key set with a synthetic spinel, silvered flinqué dial with sunray effect, blued-steel sword-shaped hands, sapphire crystal, shiny Bordeaux alligator-skin strap, steel double adjustable folding buckle. Case thickness: 11.04 mm. Water-resistant to 3 bar (approx. 30 meters / 100 feet).",
      gender: "for her",
      material: "steel",
      shape: "round",
      movement: "automatic",
      strap: "leather"
    },
    {
      title: "TANK AMÉRICAINE WATCH-M",
      popular: "popular",
      amount: 15,
      shortDescription: "Medium model, steel, leather",
      price: 4900,
      year: 2022,
      fullDescription: "Tank Américaine watch, medium model, mechanical movement with automatic winding. Steel case, octagonal crown set with a blue synthetic spinel, silver dial, blued-steel sword-shaped hands, shiny navy blue alligator leather strap, interchangeable deployant buckle. Case dimensions: 41.60 mm x 22.60 mm, thickness: 9.50 mm. Water-resistant up to 3 bar (approx. 30 meters/100 feet).",
      gender: "for him",
      material: "steel",
      shape: "rectangular",
      movement: "automatic",
      strap: "leather"
    },
    {
      title: "SANTOS-DUMONT WATCH-M",
      popular: "popular",
      amount: 20,
      shortDescription: "Large model, quartz movement, rose gold, steel, leather",
      price: 5850,
      year: 2019,
      fullDescription: "Santos-Dumont watch, large model, high autonomy quartz movement (~ 6 years). Steel case, rose gold 750/1000 bezel, steel beaded crown set with a blue synthetic cabochon-shaped spinel, satin-brushed silver dial with sunray effect, Roman numerals, blued-steel sword-shaped hands, sapphire crystal. Strap in black alligator leather, with steel ardillon buckle. Case dimensions: 43.5 mm x 31.4 mm, thickness: 7.3 mm. Water-resistant up to 3 bar (approx. 30 meters/100 feet).",
      gender: "for him",
      material: "rose gold",
      shape: "square",
      movement: "quartz",
      strap: "leather"
    },
    {
      title: "DRIVE DE CARTIER EXTRA-FLAT WATCH-M",
      popular: "popular",
      amount: 18,
      shortDescription: "Large model, hand-wound mechanical movement, steel, interchangeable metal and leather bracelets",
      price: 6150,
      year: 2020,
      fullDescription: "Drive de Cartier Extra-Flat watch, Manufacture mechanical movement with manual winding, caliber 430 MC. Case in steel, length: 38 mm, width: 39 mm, thickness: 6.6 mm, octagonal steel crown set with a blue synthetic spinel. Silvered satin-brushed dial with sunray effect, blued-steel sword-shaped hands. Sapphire crystal. Semi-matte blue alligator-skin strap, 18 mm ardillon buckle in steel. Water-resistant to 3 bar (approx. 30 meters).",
      gender: "for him",
      material: "steel",
      shape: "round",
      movement: "automatic",
      strap: "leather"
    },
    {
      title: "BALLON BLEU DE CARTIER WATCH-M",
      popular: "popular",
      amount: 13,
      shortDescription: "36 mm, mechanical movement with automatic winding, steel",
      price: 6350,
      year: 2021,
      fullDescription: "Ballon Bleu de Cartier watch, 36 mm, mechanical movement with automatic winding. Steel case, fluted crown set with a cabochon synthetic spinel. Silver guilloché dial. Blued-steel sword-shaped hands. Sapphire crystal. Steel interchangeable bracelet. Case thickness: 12.1 mm. Water-resistant up to 3 bar (approx. 30 meters/100 feet).",
      gender: "for him",
      material: "steel",
      shape: "round",
      movement: "automatic",
      strap: "metal"
    },
    {
      title: "SANTOS DE CARTIER WATCH",
      popular: "popular",
      amount: 20,
      shortDescription: "Medium model, automatic movement, steel, interchangeable metal and leather bracelets",
      price: 6800,
      year: 2018,
      fullDescription: "Santos watch, medium model, Manufacture mechanical movement with automatic winding, caliber 1847 MC. Steel case, 7-sided crown set with a faceted synthetic spinel, silvered opaline dial, steel sword-shaped hands, sapphire crystal. Steel bracelet with “SmartLink” adjustment system. Second bracelet in calfskin, with interchangeable steel folding buckle. Both bracelets are fitted with the “QuickSwitch” interchangeability system. Case width: 35.1 mm, thickness: 8.83 mm. Water-resistant up to 10 bar (approx. 100 meters/100 feet).",
      gender: "for her",
      material: "steel",
      shape: "square",
      movement: "automatic",
      strap: "metal"
    },
    {
      title: "SANTOS DE CARTIER WATCH-M",
      popular: "popular",
      amount: 18,
      shortDescription: "Medium model, automatic movement, steel, interchangeable metal and leather bracelets",
      price: 6800,
      year: 2018,
      fullDescription: "Santos watch, medium model, Manufacture mechanical movement with automatic winding, caliber 1847 MC. Steel case, 7-sided crown set with a faceted synthetic spinel, silvered opaline dial, steel sword-shaped hands, sapphire crystal. Steel bracelet with “SmartLink” adjustment system. Second bracelet in calfskin, with interchangeable steel folding buckle. Both bracelets are fitted with the “QuickSwitch” interchangeability system. Case width: 35.1 mm, thickness: 8.83 mm. Water-resistant up to 10 bar (approx. 100 meters/100 feet).",
      gender: "for him",
      material: "steel",
      shape: "square",
      movement: "automatic",
      strap: "metal"
    },
    {
      title: "TANK MC WATCH-M",
      popular: "popular",
      amount: 19,
      shortDescription: "Large model, automatic movement, steel, leather",
      price: 7350,
      year: 2021,
      fullDescription: "Tank MC watch, Manufacture mechanical movement with automatic winding, caliber 1904-PS MC, case in steel, faceted crown in steel decorated with a synthetic spinel, silvered flinqué dial, sword-shaped hands in blued steel, sapphire crystal, semi-matte black alligator-skin strap, double adjustable folding buckle in steel, calendar aperture at 3 o'clock, small second counter at 6 o'clock, sapphire case back, thickness: 9.5 mm, water-resistant to 3 bar (30 meters/100 feet).",
      gender: "for him",
      material: "steel",
      shape: "rectangular",
      movement: "automatic",
      strap: "leather"
    },
    {
      title: "PANTHÈRE DE CARTIER WATCH",
      popular: "popular",
      amount: 18,
      shortDescription: "Small model, quartz movement, yellow gold, steel",
      price: 8000,
      year: 2021,
      fullDescription: "Panthère de Cartier watch, small model, quartz movement. Case in yellow gold 750/1000 and steel, dimensions: 22 mm x 30 mm, thickness: 6 mm, crown set with a synthetic blue spinel, silvered dial, blued-steel sword-shaped hands, bracelet in yellow gold 750/1000 and steel. Water-resistant to 3 bar (approx. 30 meters).",
      gender: "for her",
      material: "yellow gold",
      shape: "square",
      movement: "quartz",
      strap: "metal"
    },
    {
      title: "PASHA DE CARTIER WATCH",
      popular: "popular",
      amount: 16,
      shortDescription: "30 mm, high autonomy quartz movement, rose gold and steel, interchangeable metal and leather straps",
      price: 8800,
      year: 2022,
      fullDescription: "Pasha de Cartier watch, 30 mm, high autonomy quartz movement. Steel case, 750/1000 rose gold bezel, fluted crown cap and crown set with synthetic spinels, opaline flinqué dial, blued steel diamond-shaped hands, bracelet in 750/1000 rose gold and steel, second strap in blue alligator leather, interchangeable steel deployant buckle. Both bracelets are fitted with the 'QuickSwitch' interchangeability system. Case diameter: 30 mm, thickness: 8.22 mm. Water-resistant up to 3 bar (approx. 30 meters/100 feet).",
      gender: "for her",
      material: "rose gold",
      shape: "round",
      movement: "quartz",
      strap: "metal"
    },
    {
      title: "SANTOS DE CARTIER CHRONOGRAPH WATCH-M",
      popular: "popular",
      amount: 12,
      shortDescription: "Extra-large model, automatic movement, steel, ADLC, interchangeable rubber and leather bracelets",
      price: 9400,
      year: 2018,
      fullDescription: "Santos watch, extra-large model, chronograph mechanical movement with automatic winding, caliber 1904 CH MC. Steel case, ADLC bezel, 7-sided crown set with a faceted black synthetic spinel, satin-brushed silver dial, black steel sword-shaped hands with luminescent material, sapphire crystal. First strap in rubber, second strap in black “Gomma” alligator leather, with steel folding buckle. Both bracelets are fitted with the “QuickSwitch” interchangeability system. Case width: 43.3 mm, case thickness: 12.5 mm. Water-resistant up to 10 bar (approx. 100 meters).",
      gender: "for him",
      material: "steel",
      shape: "square",
      movement: "automatic",
      strap: "leather"
    },
    {
      title: "TANK LOUIS CARTIER WATCH",
      popular: "popular",
      amount: 17,
      shortDescription: "Small model, quartz movement, yellow gold, leather",
      price: 9550,
      year: 2018,
      fullDescription: "Tank Louis Cartier watch, small model, quartz movement. Yellow gold 750/1000 case, beaded crown set with a sapphire cabochon, silver-grained dial, blued-steel sword-shaped hands, mineral crystal, alligator-skin strap yellow gold 750/1000 ardillon buckle. Case dimensions: 29.5 mm x 22 mm, thickness: 6.35 mm. Water-resistant to 30 meters/100 feet.",
      gender: "for her",
      material: "yellow gold",
      shape: "rectangular",
      movement: "quartz",
      strap: "leather"
    },
    {
      title: "DRIVE DE CARTIER WATCH, LARGE DATE, RETROGRADE SECOND TIME ZONE AND DAY NIGHT INDICATOR-M",
      popular: "popular",
      amount: 18,
      shortDescription: "Large model, automatic movement, steel, leather",
      price: 9550,
      year: 2020,
      fullDescription: "Drive de Cartier Second Time Zone Day/Night watch, Manufacture self-winding mechanical movement, caliber 1904-FUSEAU MC. Steel case, length: 40 mm, width: 41 mm, case thickness: 12.63 mm, octagonal steel crown set with a faceted synthetic spinel. Silvered flinqué dial, Roman numerals, blued-steel sword-shaped hands. Sapphire crystal. Black semi-matte alligator skin strap, 18 mm steel double adjustable folding buckle. Large date at 12 o'clock, retrograde second time zone at 10 o'clock, day/night indicator at half past three, small seconds at 6 o'clock, sapphire case back. Water-resistant to 3 bar (approx. 30 meters/100 feet).",
      gender: "for him",
      material: "steel",
      shape: "round",
      movement: "automatic",
      strap: "leather"
    },
    {
      title: "ROTONDE DE CARTIER WATCH, LARGE DATE, RETROGRADE SECOND TIME ZONE AND DAY NIGHT INDICATOR-M",
      popular: "popular",
      amount: 13,
      shortDescription: "42mm, automatic movement, steel, leather",
      price: 10200,
      year: 2022,
      fullDescription: "Rotonde de Cartier watch, 42 mm model, Second Time Zone Day/Night, Manufacture mechanical movement with automatic winding, caliber 1904-FU MC. Case in steel, diameter: 42 mm, thickness: 11.96 mm, fluted crown decorated with a synthetic cabochon-shaped spinel, silvered guilloché dial, apple-shaped hands in blued steel, sapphire crystal, black alligator-skin strap, 18 mm double adjustable folding buckle in steel, large date at 12 o'clock, retrograde second time zone at 10 o'clock, day/night indicator at half past three, small seconds at 6 o'clock, sapphire case back, water-resistant to 3 bar (approx. 30 meters/100 feet).",
      gender: "for him",
      material: "steel",
      shape: "round",
      movement: "automatic",
      strap: "leather"
    },
    {
      title: "BALLON BLANC DE CARTIER WATCH",
      popular: "popular",
      amount: 15,
      shortDescription: "30mm, quartz movement, rose gold, diamond, leather",
      price: 10500,
      year: 2015,
      fullDescription: "Ballon Blanc de Cartier watch, 30 mm, quartz movement. Rose gold 750/1000 case. Brilliant-cut diamond at 4 o'clock. Silvered sunray-brushed dial. Golden-finish sword-shaped hands. Sapphire crystal. Semi-matte light gray alligator-skin strap, ardillon buckle in rose gold 750/1000. Case thickness: 8.40 mm. Water-resistant to 3 bar (approx. 30 meters).",
      gender: "for her",
      material: "rose gold",
      shape: "round",
      movement: "quartz",
      strap: "leather"
    },
    {
      title: "BAIGNOIRE WATCH",
      popular: "popular",
      amount: 15,
      shortDescription: "Small model, quartz movement, yellow gold",
      price: 11000,
      year: 2020,
      fullDescription: "Baignoire watch, small model, quartz movement. Yellow gold 750/1000 case. Yellow gold 750/1000 beaded crown set with a sapphire cabochon. Silver dial, blued-steel sword-shaped hands, sapphire crystal. Strap in taupe alligator leather, with yellow gold 750/1000 ardillon buckle. Case dimensions: 32 mm x 26 mm. Thickness: 8 mm. Water-resistant to 3 bar (approx. 30 meters/100 feet).",
      gender: "for her",
      material: "yellow gold",
      shape: "round",
      movement: "quartz",
      strap: "leather"
    },
    {
      title: "TANK LOUIS CARTIER WATCH-M",
      popular: "popular",
      amount: 17,
      shortDescription: "Large model, hand-wound mechanical movement, rose gold, leather",
      price: 12800,
      year: 2018,
      fullDescription: "Tank Louis Cartier watch, large model, Manufacture mechanical movement with manual winding, caliber 8971 MC. Case in rose gold 750/1000, beaded crown set with a sapphire cabochon, silvered beaded dial, blued-steel sword-shaped hands, mineral crystal, strap in semi-matte brown alligator skin, ardillon buckle in rose gold 750/1000. Case dimensions: 33.7 mm x 25.5 mm, 6.6 mm thick. Water-resistant to 3 bar (30 meters).",
      gender: "for him",
      material: "rose gold",
      shape: "rectangular",
      movement: "automatic",
      strap: "leather"
    },
    {
      title: "RONDE LOUIS CARTIER WATCH-M",
      popular: "popular",
      amount: 14,
      shortDescription: "40mm, automatic movement, rose gold, leather",
      price: 14500,
      year: 2016,
      fullDescription: "Ronde Louis Cartier 40 mm, mechanical Manufacture with self-winding mechanism caliber 1904-PS MC, case in rose gold 750/1000, circular-grained crown set with a sapphire cabochon, silver grained dial, Roman and Arabic numerals, apple-shaped blued-steel hands, sapphire crystal, brown semi-matt alligator-skin strap, rose gold 750/1000 ardillon buckle, small seconds at 6 o'clock and date at 3 o'clock, sapphire case back, thickness 9.2 mm, water resistant to 3 bars (30 meters/100 feet).",
      gender: "for him",
      material: "rose gold",
      shape: "round",
      movement: "automatic",
      strap: "leather"
    },
    {
      title: "MINI BAIGNOIRE WATCH",
      popular: "popular",
      amount: 13,
      shortDescription: "Mini model, quartz movement, white gold, diamonds, canvas",
      price: 19400,
      year: 2016,
      fullDescription: "Baignoire watch, mini model, quartz movement. 18K rhodiumized white gold case set with 42 brilliant-cut diamonds and 12-sided crown set with a brilliant-cut diamond, totaling 0.50 carats. Dial with silvered sunray effect. Blued-steel sword-shaped hands. Sapphire crystal. Dark gray 'toile brossée' fabric strap with 9 mm 18K rhodiumized white gold ardillon buckle. Length: 25.3 mm, width: 20.79 mm, thickness: 7.73 mm. Water-resistant to 30 meters/100 feet.",
      gender: "for her",
      material: "white gold",
      shape: "round",
      movement: "quartz",
      strap: "leather"
    },
    {
      title: "TONNEAU WATCH-M",
      popular: "popular",
      amount: 15,
      shortDescription: "Large model, hand-wound mechanical movement, rose gold, leather",
      price: 23600,
      year: 2015,
      fullDescription: "Tonneau watch, large model, Manufacture mechanical movement with manual winding, caliber 1917 MC. Rose gold 750/1000 case, beaded crown set with a blue sapphire cabochon totaling 0.32 carats, sunray-effect dial, blued-steel apple-shaped hands, mineral crystal. Strap in brown semi-matte alligator leather, 12 mm rose gold 750/1000 ardillon buckle. Case dimensions: 46.3 mm x 23 mm. Thickness: 7.2 mm. Water-resistant to 3 bar (approx. 30 meters/100 feet).",
      gender: "for him",
      material: "rose gold",
      shape: "tonneau",
      movement: "automatic",
      strap: "leather"
    },
    {
      title: "PASHA DE CARTIER WATCH-M",
      popular: "popular",
      amount: 7,
      shortDescription: "41 mm, chronograph, automatic movement, 18K yellow gold, interchangeable leather straps",
      price: 24200,
      year: 2019,
      fullDescription: "Pasha de Cartier watch, 41 mm, chronograph mechanical movement with automatic winding, caliber 1904-CH MC. Yellow gold 750/1000 case, fluted crown cap, crown and push-pieces set with sapphires, silvered flinqué dial, blued-steel diamond-shaped hands, 2 alligator-skin straps, 1 dark gray and 1 navy blue with 'QuickSwitch' interchangeable system, interchangeable yellow gold 750/1000 folding buckle. Case diameter: 41 mm, thickness: 11.97 mm. Water-resistant to 10 bar (approx. 100 meters/330 feet).",
      gender: "for him",
      material: "yellow gold",
      shape: "round",
      movement: "automatic",
      strap: "leather"
    },
    {
      title: "COUSSIN DE CARTIER WATCH",
      popular: "popular",
      amount: 11,
      shortDescription: "Medium model, quartz movement, rose gold, diamonds, leather",
      price: 30500,
      year: 2020,
      fullDescription: "Coussin de Cartier watch, medium model, quartz movement. Rose gold 750/1000 case and crown set with 177 brilliant-cut diamonds totaling 4.09 carats. Dimensions: 30.4 x 31.1 mm, thickness: 7.1 mm. Sunray silver dial, gold-finish steel sword-shaped hands, beige calfskin strap, rose gold 750/1000 ardillon buckle. Water-resistant up to 3 bar (approx. 30 meters/100 feet).",
      gender: "for her",
      material: "rose gold",
      shape: "square",
      movement: "quartz",
      strap: "leather"
    },
    {
      title: "BALLON BLEU DE CARTIER WATCH",
      popular: "no",
      amount: 11,
      shortDescription: "33 mm, automatic movement, 18K rose gold, diamonds",
      price: 30700,
      year: 2022,
      fullDescription: "Ballon Bleu de Cartier watch, 33 mm, mechanical movement with automatic winding. Rose gold 750/1000 case set with 47 brilliant-cut diamonds totaling ~0.68 carats, fluted crown set with a sapphire cabochon, rose gold 750/1000 color sunray-brushed dial, blued-steel sword-shaped hands, sapphire crystal, rose gold 750/1000 interchangeable bracelet. Case thickness: 9.96 mm. Water-resistant up to 3 bar (approx. 30 meters/100 feet).",
      gender: "for her",
      material: "rose gold",
      shape: "round",
      movement: "automatic",
      strap: "metal"
    },
    {
      title: "BAIGNOIRE WATCH, SMALL MODEL",
      popular: "popular",
      amount: 10,
      shortDescription: "Small model, quartz movement, rose gold, diamonds",
      price: 36500,
      year: 2022,
      fullDescription: "Baignoire watch, small model, quartz movement. 18K rose gold case set with 41 brilliant-cut diamonds and 12-sided crown set with a brilliant-cut diamond, totaling 0.99 carats. Dial with silvered sunray effect. Blued-steel sword-shaped hands. Sapphire crystal. 18K rose gold bracelet, wrist size 165 mm. Length: 31.6 mm, width: 24.5 mm, thickness: 8.21 mm. Water-resistant to 30 meters/100 feet.",
      gender: "for her",
      material: "rose gold",
      shape: "round",
      movement: "quartz",
      strap: "metal"
    },
    {
      title: "BAIGNOIRE ALLONGÉE WATCH",
      popular: "no",
      amount: 14,
      shortDescription: "Medium model, hand-wound mechanical movement, rose gold, diamonds",
      price: 38500,
      year: 2020,
      fullDescription: "Baignoire Allongée watch, medium model, Manufacture mechanical movement with manual winding, caliber 1917 MC. Rose gold 750/1000 case set with brilliant-cut diamonds. Rose gold 750/1000 beaded crown set with a brilliant-cut diamond. Silver dial, blued-steel sword-shaped hands, sapphire crystal. Strap in taupe alligator leather, with rose gold 750/1000 ardillon buckle. Case dimensions: 47 mm x 21 mm. Thickness: 8 mm. Water-resistant up to 3 bar (approx. 30 meters/100 feet).",
      gender: "for her",
      material: "rose gold",
      shape: "round",
      movement: "automatic",
      strap: "leather"
    },
    {
      title: "TANK CHINOISE WATCH",
      popular: "no",
      amount: 9,
      shortDescription: "Large model, hand-wound mechanical skeleton movement, yellow gold, leather",
      price: 65000,
      year: 2021,
      fullDescription: "Tank Chinoise watch, skeleton, Manufacture mechanical movement with manual winding, caliber 9627 MC. Yellow gold 750/1000 case, crown in yellow gold 750/1000 set with a sapphire, sword-shaped hands in polished gold-finish steel, sapphire crystal and case back. Two straps in black and red alligator leather, yellow gold 750/1000 ardillon buckle. Hours and minutes with skeletonized bridges, covered in black and red lacquer. Movement consisting of 160 parts including 23 rubies. Movement dimensions: 26.1 mm x 23.5 mm, movement thickness: 3.9 mm, balance: 21,600 vibrations/hour, power reserve approx. 38 hours. Case dimensions: 39.50 mm x 29.16 mm, thickness: 7.7 mm. Limited edition of 100 individually numbered timepieces. Water-resistant up to 3 bar (approx. 30 meters/100 feet).",
      gender: "for her",
      material: "yellow gold",
      shape: "square",
      movement: "quartz",
      strap: "leather"
    },
    {
      title: "DRIVE DE CARTIER FLYING TOURBILLON WATCH-M",
      popular: "no",
      amount: 5,
      shortDescription: "Large model, hand-wound mechanical movement, rose gold, leather",
      price: 74000,
      year: 2018,
      fullDescription: "Drive de Cartier Flying Tourbillon watch, 40 mm, Manufacture manual winding mechanical movement, caliber 9452 MC. Watch and movement both certified 'Poinçon de Genève'. Rose gold 750/1000 case, faceted crown set with a sapphire cabochon, white galvanized guilloché dial, silvered openwork satin-finish grid with sunray effect, black transferred Roman numerals, blued-steel sword-shaped hands. Brown alligator skin strap, rose gold 750/1000 double adjustable folding buckle. Flying tourbillon complication with seconds indicated by the C-shaped tourbillon carriage. Individually numbered movement consisting of 142 parts including 19 jewels. Movement diameter: 24.9 mm, movement thickness: 4.5 mm, balance: 21,600 vibrations/hour, power reserve approx. 50 hours. Sapphire case back. Water-resistant to 3 bar (approx. 30 meters/100 feet).",
      gender: "for him",
      material: "rose gold",
      shape: "round",
      movement: "automatic",
      strap: "leather"
    },
    {
      title: "CARTIER LIBRE WATCH",
      popular: "no",
      amount: 10,
      shortDescription: "Medium model, hand-wound movement, white gold, diamonds, leather",
      price: 80500,
      year: 2017,
      fullDescription: "Cartier Libre Tortue Snake, medium model, Manufacture mechanical movement with manual winding, 430 MC. Rhodiumized white gold 750/1000 case set with 44 brilliant-cut diamonds totaling 0.25 carats, white and blue mother-of-pearl dial, rhodiumized white gold 750/1000 crown set with a special princess-cut facetted diamond totaling 0.06 carats, blued-steel sword-shaped hands, sapphire crystal, shiny black alligator leather strap, rhodiumized white gold 750/1000 ardillon buckle set with 65 brilliant-cut diamonds totaling 0.26 carats. Dimensions 40.45 mm x 32.7 mm, thickness: 6.73 mm. Water-resistant up to 3 bar (approx. 30 meters/100 feet). Numbered limited edition of 30 pieces.",
      gender: "for her",
      material: "white gold",
      shape: "round",
      movement: "automatic",
      strap: "leather"
    },
    {
      title: "RÉVÉLATION D'UNE PANTHÈRE WATCH",
      popular: "no",
      amount: 3,
      shortDescription: "37mm, hand-wound mechanical movement, rose gold, diamonds, rose gold beads",
      price: 102000,
      year: 2018,
      fullDescription: "Révélation d'une Panthère watch, 37 mm, Manufacture mechanical movement with manual winding, caliber 430 MC. Case in rose gold 750/1000 set with 45 brilliant-cut diamonds totaling 1.64 carats, black lacquer dial, panther motif in gold beads revealed by movements of the wrist, beaded crown in rose gold 750/1000 set with a brilliant-cut diamond of 0.08 carat, gold-finish steel apple-shaped hands, shiny black alligator-skin strap (additional strap in burgundy alligator skin), double adjustable folding buckle in rose gold 750/1000 set with 43 brilliant-cut diamonds totaling 0.42 carat. Water-resistant to 3 bar (approx. 30 meters).",
      gender: "for her",
      material: "rose gold",
      shape: "round",
      movement: "automatic",
      strap: "leather"
    },
    {
      title: "MAILLON DE CARTIER WATCH",
      popular: "no",
      amount: 7,
      shortDescription: "Small model, quartz movement, yellow gold, diamonds, lacquer",
      price: 127000,
      year: 2017,
      fullDescription: "Maillon de Cartier watch, quartz movement. Yellow gold 750/1000 case, crown, and bracelet set with 581 brilliant-cut diamonds totaling 9.40 carats. Dimensions: 16 x 17 mm, thickness: 6.8 mm. Gold-finish steel sword-shaped hands, black lacquer dial, case edge, and chains. Water-resistant up to 3 bar (approx. 30 meters/100 feet).",
      gender: "for her",
      material: "yellow gold",
      shape: "square",
      movement: "quartz",
      strap: "metal"
    },
    {
      title: "LA PANTHÈRE DE CARTIER WATCH",
      popular: "no",
      amount: 4,
      shortDescription: "23.6 mm, rhodiumized white gold, diamonds",
      price: 173000,
      year: 2021,
      fullDescription: "La Panthère watch, 23.6 mm, quartz movement. Rhodiumized white gold 750/1000 case set with 136 brilliant-cut diamonds totaling 1.04 carats, rhodiumized white gold 750/1000 panther head set with 297 brilliant-cut diamonds totaling 1.43 carats, pear-shaped emerald eyes totaling 0.15 carats, black lacquer spots and nose, rhodiumized white gold 750/1000 dial set with 117 diamonds totaling 0.54 carats, rhodiumized steel sword-shaped hands, rhodiumized white gold 750/1000 bracelet set with 270 brilliant-cut diamonds totaling 9.19 carats. Thickness: 7.7 mm. Water-resistant up to 3 bar (approx. 30 meters/100 feet).",
      gender: "for her",
      material: "white gold",
      shape: "round",
      movement: "quartz",
      strap: "metal"
    },
    {
      title: "RÉVÉLATION D'UNE PANTHÈRE WATCH-M",
      popular: "no",
      amount: 1,
      shortDescription: "37 mm, manual, white gold, diamonds, lacquer",
      price: 248000,
      year: 2016,
      fullDescription: "Révélation d'une Panthère watch, 37 mm, Manufacture mechanical movement with manual winding, caliber 430 MC. Rhodiumized white gold 750/1000 case set with 44 brilliant-cut diamonds totaling 1.64 carats, black lacquer dial, panther motif consisting of 650 brilliant-cut diamonds totaling 0.93 carat revealed by movements of the wrist, beaded crown set with a brilliant-cut diamond, rhodiumized steel apple-shaped hands. Bracelet in rhodiumized white gold 750/1000 set with 594 brilliant-cut diamonds totaling 16.73 carats. Thickness: 6.0 mm. Water-resistant up to 3 bar (approx. 30 meters/100 feet). Numbered limited edition of 40 pieces.",
      gender: "for him",
      material: "white gold",
      shape: "round",
      movement: "automatic",
      strap: "metal"
    },
  ]
}